### PR TITLE
Bring up to date 2

### PR DESCRIPTION
**Pull request by mdsebald**
Built and tested rpi0 and rpi4 versions using OTP-23.

I reported earlier that Windows 10 ssh into rpi0 USB OTG was working, but now it does not work for me. I was not able to determine the cause.

ssh into rpi0 on USB OTG, and ssh into rpi4 on Ethernet. from a Linux PC does work.

ssh into rpi4 on Ethernet using a Windows 10 PC does work, if the actual IP address is used (i.e. ssh circuits@192.168.1.110)

### CODE REVIEW

**Comment by fhunleth** [comment]
> Built and tested rpi0 and rpi4 versions using OTP-23.

Thanks for updating and testing this!

> I reported earlier that Windows 10 ssh into rpi0 USB OTG was working, but now it does not work for me. I was not able to determine the cause.

Hmm. I don't know why it would fail. Does it correlate to old vs. new Nerves systems?

> ssh into rpi0 on USB OTG, and ssh into rpi4 on Ethernet. from a Linux PC does work.

Great!

> ssh into rpi4 on Ethernet using a Windows 10 PC does work, if the actual IP address is used (i.e. ssh circuits@192.168.1.110)

That makes sense unless you've installed iTunes or Bonjour on your Windows PC.

**Comment by mdsebald** [comment]
Everything I read says USB OTG should work with Windows, but except for that one brief moment, it has never worked for me.  The network adapter is in the Windows device list and I can ping it, but SSH always fails (permission denied).  I'm kicking myself for not locking everything down when it started working, and figuring out exactly what the key was.  New or old Nerves version did not matter.  Also, I am running Bonjour.

**Comment by fhunleth** [comment]
Ugh.

Could you try making a WireShark capture of mDNS not working with Bonjour? It usually ends up being a Windows or a network configuration issue where multicast is being dropped by an access point. However, since it was working for you at one time, I’m not sure why it would have changed.

**Comment by fhunleth** [comment]
More updates happened between this branch and now. I'm going to cherry-pick commits from here manually...

**Comment by fhunleth** [comment]
Cherry-picked. This was helpful. Thanks!

**Pull request closed without merging**
